server:
  port: 9000

management:
  security:
    enabled: false

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

integration:
  stores:
    uri: http://localhost:8081
    test: '{cipher}316f8cdbb776c23e679bf209014788a6eab7522f48f97114328c2c9388e6b3c1'

stores:
  ribbon:
    ServerListRefreshInterval: 1000

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    region: default
    registryFetchIntervalSeconds: 5
    availabilityZones: 
      default: http://localhost:8761/eureka/

# For demo only allow more hystrix connections
hystrix:
  stream:
    maxConcurrentConnections: 20
    bus:
      enabled: true

spring:
  rabbitmq:
    addresses: localhost:5672

logging:
  level:
    com.netflix.discovery: 'OFF'

---
spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: Megazone00!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
