server:
  port: 9900
logging:
  level:
    com.netflix.discovery: 'OFF'
    com.netflix.zuul: 'OFF'
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:8761/eureka/
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ServerListRefreshInterval: 5000
  ConnectTimeout: 3000
  ReadTimeout: 60000

spring:
  cloud:
    gateway:
      routes:
        - id: stores
          uri: lb://stores
          predicates:
            - Path=/stores/**
        - id: customers
          uri: lb://customers
          predicates:
          - Path=/customers/**
        - id: root
          uri: no://op
          predicates:
          - Path=/
          filters:
          - RedirectTo=302, /index.html#/customers

management:
  endpoints:
    web:
      exposure:
        include: '*'
